# -*- coding: utf-8 -*-
"""ACL Injury Prevention Height.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFtksGOPTlDoOCtDKSuqRZhdHjsh6vkQ
"""

import math
import matplotlib.pyplot as plt
import numpy as np

def calculate_x(height, theta):
    h = height
    theta_rad = math.radians(theta)
    x = (h / 2) - (h / 2) * math.sin((math.pi- theta_rad)/2)

    return x

height = float(input("Enter the height of the person (in cm): "))

thetas = np.arange(0, 181, 5)  # Range of theta values from 0 to 180 degrees with a step of 5 degrees
displacements = [calculate_x(height, theta) for theta in thetas]

plt.plot(thetas, displacements)
plt.xlabel("Theta (degrees)")
plt.ylabel("Displacement (cm)")
plt.title("Displacement vs. Theta")
plt.grid(True)
plt.show()